### ISSUE TITLE
Dont Load Movie Players if Stream Chosen

### ISSUE THREAD

**Issue by JesseScott** [JesseScott/SecondStory-Android#19]
java.lang.NullPointerException: Attempt to invoke virtual method 'android.content.Intent android.content.Intent.putExtra(java.lang.String, int)' on a null object reference
at com.theonlyanimal.ar.VideoPlayerHelper.play(VideoPlayerHelper.java:436)
at com.theonlyanimal.ar.VideoPlaybackRenderer.onDrawFrame(VideoPlaybackRenderer.java:304)
at android.opengl.GLSurfaceView$GLThread.guardedRun(GLSurfaceView.java:1522)
at android.opengl.GLSurfaceView$GLThread.run(GLSurfaceView.java:1239)

**Comment by JesseScott** [comment]
you know... i could also test for null...

**Comment by Ericrhysmiller** [comment]
um.  lost me at ‘test for null’ sorry
not intended for me?

On May 1, 2015, at 9:59 PM, Jesse Scott <notifications@github.com> wrote:

> you know... i could also test for null...
> 
> —
> Reply to this email directly or view it on GitHub.
> 

Eric Rhys Miller
604-910-0601 (mobile)

**Comment by JesseScott** [comment]
Not intended for you :D 
thanks though! 
If I ever actually need you to respond to any of this, I'll tag you directly with @Ericrhysmiller
